### ISSUE TITLE
Task TS01 - Testar fluxos de conversação

### ISSUE THREAD

**Issue by thiagoiferreira** [fga-eps-mds/2019.1-PyLearner#104]
# Task TS01 - Testar fluxos de conversação
---
### Descrição:
Nesta issue, o responsável ficará por testar todos os fluxos de conversção do bot desenvolvidos nas  US's 1, 2, 4, 14 e 15. Os fluxos devem corresponder aos criterios propostos em cada US individual.

### Critérios de Aceitação
Para que essa issue seja aceita, é necessário que tenham sido testados os cenários das:
- [x] US01
- [x] US02
- [x] US04
- [x] US14
- [x] US15

**Comment by davialvb** [comment]
Casos testados, já levantamos as melhoras para as itents, stories e domain. Serão abertas novas issues para isso!
