### ISSUE TITLE
Create issue template

### ISSUE THREAD

**Issue by thiagoiferreira** [fga-eps-mds/2019.1-PyLearner#11]
- [x] Create github issue's template for adequating the project to the [recommended community standards](https://github.com/fga-eps-mds/2019.1-Grupo-10/community)

**Comment by davialvb** [comment]
I just add markdown files to the .github/ISSUE_TEMPLATE/ directory. I reference them by adding ?template=filename.md to the new issue URL. I make using a standard template (.github/ISSUE_TEMPLATE.md) with a list of your available templates. just click on which template you want.

**Comment by thiagoiferreira** [comment]
Looks great! Gonna try and see if anything is missing as the recommended community standard is still not identified by github
![image](https://user-images.githubusercontent.com/26505480/54820570-7429d680-4c7e-11e9-9587-ffce43d3ea5c.png)
