### ISSUE TITLE
Task TS01 - Treinamento do bot

### ISSUE THREAD

**Issue by carlosaragon** [fga-eps-mds/2019.1-PyLearner#110]
# Task TS01 - Treinamento do bot

### Descrição:
Nesta issue, o responsável deverá treinar o bot com os cenários correspondentes aos fluxos de conversação desenvolvidos nas  US's 1, 2, 4, 14 e 15. 

### Critérios de Aceitação
Para que essa issue seja aceita, é necessário que tenham sido treinados os cenários das:
- [x] US01
- [x] US02
- [x] US04
- [x] US14
- [x] US15

**Comment by davialvb** [comment]
Treinamento feito e bot já funcionando.
