### ISSUE TITLE
US 19 - Tutorial completo Iris Flower

### ISSUE THREAD

**Issue by carlosaragon** [fga-eps-mds/2019.1-PyLearner#111]
# US 19 - Tutorial completo Iris Flower
---
### Descrição:
Nesse US o responsavel deverá desenvolver um jupyter notebook para adptar o tutorial Iris Flower para o modelo interativo.

### Critérios de Aceitação
- [x] Cada etapa do codigo explicado deve ser seguido por uma célula para teste.

### Tarefas
- [x] Analisar o tutorial do Iris Flower.
- [x] Adptar para o modelo jupyter.

**Comment by alexportof** [comment]
Adicionei o Tutorial completo no Jupyter Notebook,arquivo Iris Flower.ipynb dentro da pasta Tutoriais.Tive problemas para carregar as imagens contidas no folder dentro do arquivo.É preciso resolver isso e melhorar a visualização do treinamento.

**Comment by thiagoiferreira** [comment]
Pull Request aceito, fechando issue.
