### ISSUE TITLE
Reorganização EAP

### ISSUE THREAD

**Issue by carlosaragon** [fga-eps-mds/2019.1-PyLearner#115]
Reorganização EAP
---
Mudança dos esquema de cores e retirada de itens que não cabem no diagrama.

**Comment by RochaCarla** [comment]
não está claro quais criterios de aceitação, nem como a issue agrega valor. @carlosaragon , favor me procurar depois da aula..

**Comment by thiagoiferreira** [comment]
Revisando pela descrição, a issue foi concluída e aceita
