### ISSUE TITLE
Refatoração dos dados para treinamento do bot

### ISSUE THREAD

**Issue by davialvb** [fga-eps-mds/2019.1-PyLearner#116]
### Descrição:
Uma refatoração nos dados deve ser feita para um melhor fluxo de conversa do Bot. É esperado que ele responda melhor determinada duvida.

### Critérios de Aceitação
Critérios de aceitação para a Issue ser aceita.
- [x] Todos os arquivos devidamente refatorados
- [x] Nenhum erro de formatação

### Tarefas
Documentos que devem ser refatorados. As tarefas devem garantir o perfeito funcionamento da Issue.
- [x] missing_data.md
- [x] json_import.md
- [x] interactions.md
- [x] importacao_CSV.md
- [x] histogram.md
- [x] correlation.md

**Comment by Eugeniosales** [comment]
Issue concluída e pronta para a revisão.

**Comment by davialvb** [comment]
Tudo certo, PR já foi aceito!
