### ISSUE TITLE
Adição de dados para melhoria do bot

### ISSUE THREAD

**Issue by davialvb** [fga-eps-mds/2019.1-PyLearner#117]
# Adição de dados para melhoria do bot
---
### Descrição:
Após verificar a fluidez da conversa com o bot, foi possivel notar que faltam alguns detalhes para que ele responda melhor as duvidas. 

### Critérios de Aceitação
Critérios de aceitação para a Issue ser aceita.
- [x] Nenhum erro de formatação
- [x] Intents, stories e domain adicionados corretamente

### Tarefas
* Criação das intents:
    - [x] Ajuda
    - [x] Estado_bot
    - [x] Sobre_jupyter
    - [x] Sobre_Pyter
* Criação das stories:
    - [x] Ajuda
    - [x] Estado_bot
    - [x] Sobre_jupyter
    - [x] Sobre_Pyter
- [x] Adição das intents, actions e templates no domain
- [x] Refatorar intent <b>cumprimentar</b>

**Comment by Eugeniosales** [comment]
Issue concluída e pronta para revisão.

**Comment by davialvb** [comment]
Revisada, abram o PR!!

**Comment by thiagoiferreira** [comment]
PR aceito
