### ISSUE TITLE
US 21 - Tutorial Machine Learning do Problema do Titanic

### ISSUE THREAD

**Issue by thiagoiferreira** [fga-eps-mds/2019.1-PyLearner#118]
### Descrição:
Nesta história de usuário, o responsável deverá criar um tutorial interativo para o usuário, de forma que possa ser realizado um passo a passo, no Jupyter notebook. O tutorial a ser criado deve ser baseado em tutorias do problema do Titanic.

### Critérios de Aceitação
- [ ] Cada etapa do código explicado deve ser seguido por uma célula para teste.

### Tarefas
- [ ] Fazer um estudo destinado ao problema.
- [ ] Modelo do tutorial adaptado para o Jupyter

**Comment by ZarathosDeath** [comment]
Foi usado esse [tutorial](https://www.kaggle.com/shikhar96/titanic-prediction-using-scikit-learn-tutorial) do Kaggle.

**Comment by ZarathosDeath** [comment]
Enviado para revisão
