### ISSUE TITLE
US 20 - Tutorial Machine Learning do Problema MNIST

### ISSUE THREAD

**Issue by thiagoiferreira** [fga-eps-mds/2019.1-PyLearner#120]
### Descrição:
Nesta história de usuário, o responsável deverá criar um tutorial interativo para o usuário, de forma que possa ser realizado um passo a passo, no Jupyter notebook. O tutorial a ser criado deve ser baseado em tutorias do problema do Titanic.

### Critérios de Aceitação
- [x] Cada etapa do código explicado deve ser seguido por uma célula para teste.

### Tarefas
- [x] Fazer um estudo destinado ao problema.
- [x] Modelo do tutorial adaptado para o Jupyter

**Comment by joao15victor08** [comment]
[Tutorial](https://github.com/pylearner-bot/pylearner-rasa/blob/US20-tutorial-mnist/tutoriais/mnist.ipynb) finalizado e colocado para review.

**Comment by joao15victor08** [comment]
Foi usado esse [tutorial](https://scikit-learn.org/stable/tutorial/basic/tutorial.html#introduction) como base.

**Comment by thiagoiferreira** [comment]
PR aceito
