### ISSUE TITLE
US05 - Eu como usuário desejo saber como transformar dados categóricos

### ISSUE THREAD

**Issue by thiagoiferreira** [fga-eps-mds/2019.1-PyLearner#121]
# US05 - Eu como usuário desejo saber como transformar dados categóricos
---
### Descrição:
Nessa história de usuário o desenvolvedor deverá preparar o material para que o usuário do bot possa tirar dúvidas com respeito ao tópico de transformação de dados categóricos.
O responsável deverá tratar de todas as tarefas que compõe essa história de forma sequencial, para que essa seja completa.

### Critérios de Aceitação
Para a aceitação desta história, a entrega deve cumprir os seguintes critérios de aceitação:
- [x] Todo o dialogo do bot deve estar em português.
- [x] As respostas devem ser escritas de forma compreensível ao usuário.
- [x] As respostas do bot devem ser funcionais e corretas de forma que o usuário seja capaz de usar a informação recebida sem problemas.
- [x] As respostas devem ser breves e objetivas, de forma a melhorar a usabilidade do bto

### Tarefas
Para a aceitação desta história, deve ter as seguintes tasks constituintes concluídas:
- [x] [Documentação de Estudo do tema](https://github.com/fga-eps-mds/2019.1-PyLearner/issues/)
- [x] [Intents, Criados](https://github.com/fga-eps-mds/2019.1-PyLearner/issues/)
- [x] [Cenários/Histórias criadas](https://github.com/fga-eps-mds/2019.1-PyLearner/issues/)

**Comment by Mexazonic** [comment]
Documentação de Estudo do Tema criada. 
Aguardo Feedback para poder prosseguir nas criações das intents, actions e stories.
A documentação para análise se encontra bem <a href="https://github.com/fga-eps-mds/2019.1-PyLearner/blob/master/docs/documentation-mds/Documento-da-US05.md">aqui</a>.

**Comment by davialvb** [comment]
Tudo certo, pode iniciar quanto antes as intents, actions e stories.
