### ISSUE TITLE
US03 - Eu como usuário desejo saber como importar dados de um excel

### ISSUE THREAD

**Issue by thiagoiferreira** [fga-eps-mds/2019.1-PyLearner#122]
# US03 - Eu como usuário desejo saber como importar dados de um excel
---
### Descrição:
Nessa história de usuário o desenvolvedor deverá preparar o material para que o usuário do bot possa tirar dúvidas com respeito a importação de dados de uma planilha no excel.
O responsável deverá tratar de todas as tarefas que compõe essa história de forma sequencial, para que essa seja completa.

### Critérios de Aceitação
Para a aceitação desta história, a entrega deve cumprir os seguintes critérios de aceitação:
- [x] Todo o dialogo do bot deve estar em português.
- [x] As respostas devem ser escritas de forma compreensível ao usuário.
- [x] As respostas do bot devem ser funcionais e corretas de forma que o usuário seja capaz de usar a informação recebida sem problemas.
- [x] As respostas devem ser breves e objetivas, de forma a melhorar a usabilidade do bot

### Tarefas
Para a aceitação desta história, deve ter as seguintes tasks constituintes concluídas:
- [x] Incrementar documentação de importação de dados
- [x] Intents, actions e templates Criados
- [x] Cenários e Histórias criadas

**Comment by alexportof** [comment]
Documentação dessa US [está aqui](https://github.com/fga-eps-mds/2019.1-PyLearner/blob/master/docs/documentation-mds/Documento-da-US03.md).Aguardo sugestões de melhoria do documento.

**Comment by alexportof** [comment]
Intents,stories e utters adicionadas [aqui](https://github.com/pylearner-bot/pylearner-rasa/tree/US19-tutorial-iris-flower),acham necessário adicionar mais?

**Comment by davialvb** [comment]
A fins de padronização, siga o exemplo da "utter_calcular_correlacao" para deixar o text da sua utter mais facil de entender. Arrume a formatação na stories.

**Comment by alexportof** [comment]
É necessário adicionar as fotos tambem?Como consta na utter_calcular_correlacao

**Comment by davialvb** [comment]
Não!! Olha ela na devel...

**Comment by alexportof** [comment]
[Corrigido e colocado para avaliação](https://github.com/pylearner-bot/pylearner-rasa/tree/US03-importar-excel/bot)
