### ISSUE TITLE
US16 - Eu como usuário desejo saber como visualizar um relatório de classificação

### ISSUE THREAD

**Issue by thiagoiferreira** [fga-eps-mds/2019.1-PyLearner#123]
# US16 - Eu como usuário desejo saber como visualizar um relatório de classificação
---
### Descrição:
Nessa história de usuário o desenvolvedor deverá preparar o material para que o usuário do bot possa tirar dúvidas com respeito ao tópico de visualização de um relatório de classificação
O responsável deverá tratar de todas as tarefas que compõe essa história de forma sequencial, para que essa seja completa.

### Critérios de Aceitação
Para a aceitação desta história, a entrega deve cumprir os seguintes critérios de aceitação:
- [x] Todo o dialogo do bot deve estar em português.
- [x] As respostas devem ser escritas de forma compreensível ao usuário.
- [x] As respostas do bot devem ser funcionais e corretas de forma que o usuário seja capaz de usar a informação recebida sem problemas.
- [x] As respostas devem ser breves e objetivas, de forma a melhorar a usabilidade do bot

### Tarefas
Para a aceitação desta história, deve ter as seguintes tasks constituintes concluídas:
- [x] [Documentação de Estudo do tema](https://github.com/fga-eps-mds/2019.1-PyLearner/issues/)
- [x] [Intents, actions e templates Criados](https://github.com/fga-eps-mds/2019.1-PyLearner/issues/)
- [x] [Cenários/Histórias criadas](https://github.com/fga-eps-mds/2019.1-PyLearner/issues/)

**Comment by alexportof** [comment]
Pessoal,estou meio perdido nessa US,relatório de classificação é muito vago,classificação de que?Se alguem puder me ajudar seria otimo!Porque sei nem o que pesquisar no google kkk nao to encontrando nada relacionado a machine learning na busca

**Comment by carlosaragon** [comment]
A ideia é falar sobre os reports de resultados que são gerados por uma classificação, esse link vai te dar um norte. https://scikit-learn.org/stable/modules/generated/sklearn.metrics.classification_report.html#

**Comment by alexportof** [comment]
Issue finalizada e colocada para revisao! [Documentação](https://github.com/fga-eps-mds/2019.1-PyLearner/blob/master/docs/documentation-mds/Documento-da-US16.md) e [Branch](https://github.com/pylearner-bot/pylearner-rasa/tree/US16-relatorio-classificacao)
