### ISSUE TITLE
US17 - Eu como usuário desejo saber como visualizar uma matriz de confusão

### ISSUE THREAD

**Issue by thiagoiferreira** [fga-eps-mds/2019.1-PyLearner#124]
# US17 - Eu como usuário desejo saber como visualizar uma matriz de confusão
---
### Descrição:
Nessa história de usuário o desenvolvedor deverá preparar o material para que o usuário do bot possa tirar dúvidas com respeito ao tópico de visualização de uma matriz de confusão
O responsável deverá tratar de todas as tarefas que compõe essa história de forma sequencial, para que essa seja completa.

### Critérios de Aceitação
Para a aceitação desta história, a entrega deve cumprir os seguintes critérios de aceitação:
- [x] Todo o dialogo do bot deve estar em português.
- [x] As respostas devem ser escritas de forma compreensível ao usuário.
- [x] As respostas do bot devem ser funcionais e corretas de forma que o usuário seja capaz de usar a informação recebida sem problemas.
- [x] As respostas devem ser breves e objetivas, de forma a melhorar a usabilidade do bot

### Tarefas
Para a aceitação desta história, deve ter as seguintes tasks constituintes concluídas:
- [x] [Documentação de Estudo do tema](https://github.com/fga-eps-mds/2019.1-PyLearner/issues/)
- [x] [Intents, actions e templates Criados](https://github.com/fga-eps-mds/2019.1-PyLearner/issues/)
- [x] [Cenários/Histórias criadas](https://github.com/fga-eps-mds/2019.1-PyLearner/issues/)

**Comment by Eugeniosales** [comment]
Adcionado para revisão. [Stories](https://github.com/pylearner-bot/pylearner-rasa/blob/US17-Matriz-de-confusao/bot/data/stories/confusion-matrix.md), [Intents](https://github.com/pylearner-bot/pylearner-rasa/blob/US17-Matriz-de-confusao/bot/data/intents/confusion-matrix.md), [Documento](https://github.com/fga-eps-mds/2019.1-PyLearner/blob/master/docs/documentation-mds/Documento-da-US17.md)
