### ISSUE TITLE
US08 - Eu como usuário desejo saber quais modelos usar para um problema de classificação

### ISSUE THREAD

**Issue by thiagoiferreira** [fga-eps-mds/2019.1-PyLearner#125]
# US08 - Eu como usuário desejo saber quais modelos usar para um problema de classificação
### Descrição:
Nessa história de usuário o desenvolvedor deverá preparar o material para que o usuário do bot possa tirar dúvidas com respeito a utilização de determinados modelos em problemas específicos de machine learning. 
O responsável deverá tratar de todas as tarefas que compõe essa história de forma sequencial, para que essa seja completa, abordando a maior parte dos modelos e tipos de problemas que este pode solucionar

### Critérios de Aceitação
Para a aceitação desta história, a entrega deve cumprir os seguintes critérios de aceitação:
- [ ] Todo o dialogo do bot deve estar em português.
- [ ] As respostas devem ser escritas de forma compreensível ao usuário.
- [ ] As respostas do bot devem ser funcionais e corretas de forma que o usuário seja capaz de usar a informação recebida sem problemas.
- [ ] As respostas devem ser breves e objetivas, de forma a melhorar a usabilidade do bot

### Tarefas
Para a aceitação desta história, deve ter as seguintes tasks constituintes concluídas:
- [x] [Documentação de Estudo do tema](https://github.com/fga-eps-mds/2019.1-PyLearner/issues/)
- [x] [Intents, actions e templates Criados](https://github.com/fga-eps-mds/2019.1-PyLearner/issues/)
- [x] [Cenários/Histórias criadas](https://github.com/fga-eps-mds/2019.1-PyLearner/issues/)

**Comment by Eugeniosales** [comment]
Essa Issue se trata, apenas, de modelos de aprendizado supervisionado?

**Comment by thiagoiferreira** [comment]
Sim

**Comment by joao15victor08** [comment]
Parte do [documento de estudos](https://github.com/fga-eps-mds/2019.1-PyLearner/blob/master/docs/documentation-mds/Documento-da-US08.md) finalizado.
Tópicos 4, 5 e 6.

**Comment by Eugeniosales** [comment]
Tópicos 1, 2 e 3 finalizados também do  [documento de estudo](https://github.com/fga-eps-mds/2019.1-PyLearner/blob/master/docs/documentation-mds/Documento-da-US08.md)
