### ISSUE TITLE
Atualizar Guia de Estilo para que essa fique mais adequada ao projeto

### ISSUE THREAD

**Issue by thiagoiferreira** [fga-eps-mds/2019.1-PyLearner#129]
# Atualizar Guia de Estilo para que essa fique mais adequada ao projeto
### Descrição:
A guia de estilo criada no início do projeto acabou por se tornar em grande parte obsoleta, não atingindo as necessidades do projeto. Essa issue é focada na melhoria desse documento, determinando um guia de estilo adequado para o desenvolvimento de um bot em rasa.

### Tarefas
- [x] Linters
- [x] Regras dos linters adicionada aos documentos

**Comment by gabrielziegler3** [comment]
Issue não iniciada na sprint planejada e será passada para sprint 8 como **débito**

**Comment by thiagoiferreira** [comment]
Adicionei ao nosso documento de guias de estilo, as regras do markdownlint, que serão usadas para padronização da documentação da equipe e fiz um maior detalhamento do flake8.
