### ISSUE TITLE
Documento de Arquitetura

### ISSUE THREAD

**Issue by thiagoiferreira** [fga-eps-mds/2019.1-PyLearner#13]
Criar e desenvolver documento de Arquitetura.

Para aceitação do documento, este deverá conter:
- [x] [Introdução](https://github.com/fga-eps-mds/2019.1-PyLearner/issues/43)
- [x] [Representaão da Arquitetura](https://github.com/fga-eps-mds/2019.1-PyLearner/issues/44)
- [x] [Metas e Restrições de Arquitetura](https://github.com/fga-eps-mds/2019.1-PyLearner/issues/45)
- [x] [Visão Lógica](https://github.com/fga-eps-mds/2019.1-PyLearner/issues/48)

**Comment by thiagoiferreira** [comment]
@davialvb, acredito que tenha uma parte do documento que você deva fazer, assim como ajudar a piazada com as dúvidas

**Comment by thiagoiferreira** [comment]
All the topics were closed, need final review for closing this issue

**Comment by davialvb** [comment]
Documento finalizado, terá de ser revisado e deverão ser arrumados: 
* Formatação, alguns erros ortográficos e alguns outros detalhes. 

Após esses problemas resolvidos a issue sera fechada.
