### ISSUE TITLE
US09 - Eu como usuário desejo saber quais métricas usar para modelos de regressão 

### ISSUE THREAD

**Issue by davialvb** [fga-eps-mds/2019.1-PyLearner#132]
# US09 - Eu como usuário desejo saber quais métricas usar para modelos de regressão 
---
### Descrição:
Para um melhor entendimento dentro da area de machine learning abordamos o tema métricas para modelos de regressão . O desenvolvedor deverá preparar o material para o treinamento do bot no tema citado.

Links de apoio:
[Model Evaluation](https://scikit-learn.org/stable/modules/model_evaluation.html)

### Critérios de Aceitação
- [ ] Intents, actions e stories dentro do padrão aceitavel.
- [ ] Correta formatação do markdown em todos os arquivos criados ou modificados

### Tarefas
Para a aceitação desta história, deve ter as seguintes tasks constituintes concluídas:
- [x] Documentação de Estudo sobre **explained_variance**
- [x] Documentação de Estudo sobre **r2_score**
- [x] Intents, actions e templates Criados sobre **explained_variance**
- [x] Intents, actions e templates Criados sobre **r2_score**
- [x] Cenários/Histórias criadas sobre **explained_variance**
- [x] Cenários/Histórias criadas sobre **r2_score**

**Comment by joao15victor08** [comment]
[Documento](https://github.com/fga-eps-mds/2019.1-PyLearner/blob/master/docs/documentation-mds/Documento-da-US09.md) sobre R2 score finalizado.

**Comment by ZarathosDeath** [comment]
[Documento](https://github.com/fga-eps-mds/2019.1-PyLearner/blob/master/docs/documentation-mds/Documento-da-US09.md) atualizado com Explained Variance score

**Comment by ZarathosDeath** [comment]
Criado intents, actions e templates para explained variance. Enviado para revisão
