### ISSUE TITLE
Refatorar o README

### ISSUE THREAD

**Issue by davialvb** [fga-eps-mds/2019.1-PyLearner#134]
# Refatorar o README

## Descrição
O README atual não está bom o suficiente para apresentação do produto. Há necessidades de melhoria.

## Tarefa
- [x] README refatorado

**Comment by gabrielziegler3** [comment]
Os dois README foram atualizados? Onde estão os novos?

**Comment by davialvb** [comment]
O README que foi modificado foi apenas o do repositorio de [código](https://github.com/pylearner-bot/pylearner-rasa)
