### ISSUE TITLE
Refatorar Roadmap Tech Lead

### ISSUE THREAD

**Issue by davialvb** [fga-eps-mds/2019.1-PyLearner#137]
# Refatorar Roadmap Tech Lead
### Descrição:
Refatoração do documento Roadmap para adaptação e adição de tarefas relacionadas ao papel.

### Critérios de Aceitação
- [ ] Refatoração do roadmap feita

**Comment by gabrielziegler3** [comment]
[Roadmap](https://github.com/fga-eps-mds/2019.1-PyLearner/blob/master/docs/roadmap/Roadmap-TechLead.md) adicionado novas tarefas do novo techlead.
