### ISSUE TITLE
Lançar Release do Produto

### ISSUE THREAD

**Issue by gabrielziegler3** [fga-eps-mds/2019.1-PyLearner#144]
- [x] Release funcional do produto no GitHub seguindo as [convenções](https://semver.org/) do GH para `tag` de versionamento.
- [x] Descrição de todas funcionalidades contempladas na release

**Comment by thiagoiferreira** [comment]
Release feita:
https://github.com/pylearner-bot/pylearner-rasa/releases/tag/v0.1.0

**Comment by gabrielziegler3** [comment]
Antes de mover para `done` mova para `Review/QA` para que possa haver a revisão do que foi feito.
- [Definição de Done](https://fga-eps-mds.github.io/2019.1-PyLearner/policies/Definicao-Done/).

**Comment by davialvb** [comment]
Para que seja seguido o criterio de aceitação "Release funcional" deve-se resolver a issue [158](https://github.com/fga-eps-mds/2019.1-PyLearner/issues/158). Há necessidades de reparo para que a release do produto esteja completa.

**Comment by thiagoiferreira** [comment]
A issue de erro não condiz especificamente com a master, o problema está na máquina no usuário, visto que a branch está funcionando nos computadores dos demais membros da equipe, deixarei a issue aberta mas tirarei a dependência da release da mesma.
