### ISSUE TITLE
Make EAP document

### ISSUE THREAD

**Issue by thiagoiferreira** [fga-eps-mds/2019.1-PyLearner#15]
Project Owner to work on :
- [x] Writing analitic project strucuture (EAP) documentation

**Comment by gabrielziegler3** [comment]
@carlosaragon como está o progresso dessa issue? Não está havendo transparência.

**Comment by carlosaragon** [comment]
Documento concluido e ja disponovel no repositorio.

**Comment by gabrielziegler3** [comment]
a imagem do documento nao foi subida

**Comment by gabrielziegler3** [comment]
@all-contributors please add @carlosaragon  for docs
