### ISSUE TITLE
Estudo de viabilidade de integração Google Assistant - Rasa

### ISSUE THREAD

**Issue by gabrielziegler3** [fga-eps-mds/2019.1-PyLearner#151]
- [x] Estudar a viabilidade da integração dos dois serviços.
- [ ] Postar na issue os referenciais do estudo e a conclusão da pesquisa.

**Comment by gabrielziegler3** [comment]
Como anda o estudo de viabilidade do Google Assistant? Alguma conclusão, referências, ideias?

**Comment by carlosaragon** [comment]
Eu estou fazendo esse estudo por meio de um tutorial que ensina como conectar um rasa bot no google assistent, porem a dificuldade técnica é maior do que a esperada no planejamento,devido as dificuldades que estou enfrentando em conectar o bot com a API do google.

**Comment by carlosaragon** [comment]
O estudo demonstrou que a integração com a plataforma do google é plausível, porem é mais difícil do que o esperado na primeira analise. Dado essa conclusão podemos definir que esse serviço será incluido no projeto.
