### ISSUE TITLE
Integrar protótipo HF com da aplicação front-end 

### ISSUE THREAD

**Issue by gabrielziegler3** [fga-eps-mds/2019.1-PyLearner#152]
- [x] Usar HTML do protótipo HF no projeto utilizando o `docker`  de desenvolvimento mantendo todas as funcionalidades.

**Comment by davialvb** [comment]
Essa issue foi descontinuada pois o prototipo de alta fidelidade já estava implementado para manter as funcionalidades da aplicação. Ou seja, a aparencia do prototipo já está aplicada ao jupyter na devel!
