### ISSUE TITLE
Análise de qualidade de código

### ISSUE THREAD

**Issue by gabrielziegler3** [fga-eps-mds/2019.1-PyLearner#155]
- [x] Efetuar análise de qualidade de código Python com Flake8 na execução do `docker`
- [x] Efetuar análise de qualidade documentação/chatbot insumos Markdown na execução do `docker`
- [x] Adicionar [badge](http://shields.io) com a qualidade do código medido para cada uma.

**Comment by thiagoiferreira** [comment]
Usei esse artigo e alguns outros para referência quanto ao flake8:
https://simpleisbetterthancomplex.com/packages/2016/08/05/flake8.html
