### ISSUE TITLE
US10 - Eu, como usuário, gostaria de saber quais modelos usar para regressão

### ISSUE THREAD

**Issue by gabrielziegler3** [fga-eps-mds/2019.1-PyLearner#156]
# US10 - Eu, como usuário, gostaria de saber quais modelos usar para regressão
---
### Descrição:
Para um melhor entendimento dentro da area de machine learning abordamos o tema voltado a quais os modelos usar para regressão. O desenvolvedor deverá preparar o material para o treinamento do bot no tema citado.

Link de apoio:
[Polynomial regression](https://scikit-learn.org/stable/modules/linear_model.html#polynomial-regression-extending-linear-models-with-basis-functions)
[Bayesian Regression](https://scikit-learn.org/stable/modules/linear_model.html#bayesian-regression)

### Critérios de Aceitação
- [x] Intents, actions e stories dentro do padrão aceitavel.
- [x] Correta formatação do markdown em todos os arquivos criados ou modificados

### Tarefas
Para a aceitação desta história, deve ter as seguintes tasks constituintes concluídas:
- [x] Documentação de Estudo do tema Polynomial regression e Bayesian Regression
- [x] Intents, actions e templates criados do tema Polynomial regression e Bayesian Regression
- [x] Cenários/Histórias criadas do tema Polynomial regression e Bayesian Regression

**Comment by joao15victor08** [comment]
[Documento](https://github.com/fga-eps-mds/2019.1-PyLearner/blob/master/docs/documentation-mds/Documento-da-US10.md) de estudo finalizado.

**Comment by alexportof** [comment]
[Pull request aberto](https://github.com/pylearner-bot/pylearner-rasa/pull/40)
