### ISSUE TITLE
[URGENTE!] - Erro que impossibilita uso do bot na branch master

### ISSUE THREAD

**Issue by davialvb** [fga-eps-mds/2019.1-PyLearner#158]
## Erro que impossibilita uso do bot na branch master

* **Estou enviando um ...**
  - [x] Bug

* **Qual o comportamento atual?**
Ao buildar alguns erros aparecem e impossibilitam o bom funcionamento da aplicação.
![image](https://user-images.githubusercontent.com/34287081/57635578-f5bf2600-7596-11e9-81a2-d622dde31654.png)
![image](https://user-images.githubusercontent.com/34287081/57635639-15564e80-7597-11e9-880c-3d846ac8f98e.png)
![image](https://user-images.githubusercontent.com/34287081/57635652-1d15f300-7597-11e9-83b0-9e923154cb15.png)

* **Qual o comportamento esperado?**
Após buildar ser possivel a vizualização do chat dentro do ambiente jupyter.

* **Outras Informações**
Acredito que isso seja de extrema urgencia devido ao uso da aplicação por terceiros e até mesmo para os testes serem aplicados no bot.

**Comment by thiagoiferreira** [comment]
Não consegui reproduzir o erro, rodei a master e subiu tudo corretamente, to com a aplicação funcionando aqui. Você fez alguma coisa específica pra que eu possa tentar reproduzir o erro?
![image](https://user-images.githubusercontent.com/26505480/57656656-6ffba480-75af-11e9-8c01-a3e55f0beb98.png)

**Comment by davialvb** [comment]
Sua branch está atualizada? 
Meu jupyter fica assim
![image](https://user-images.githubusercontent.com/34287081/57662722-47d86980-75e0-11e9-8d0a-d9a21ca493d1.png)

E isso aparece
![image](https://user-images.githubusercontent.com/34287081/57662741-5c1c6680-75e0-11e9-9ddb-0425795f6c15.png)

**Comment by thiagoiferreira** [comment]
Está sim, fiz um clone novo pra garantir também. Tenta fazer o mesmo e vê se continua dando erro.

**Comment by gabrielziegler3** [comment]
Qual a conclusão desse possível bug? Posso aprovar a release [#144](https://github.com/fga-eps-mds/2019.1-PyLearner/issues/144) que possui dependencia?

**Comment by davialvb** [comment]
Clonei o repositorio novamente e limpei as imagens do docker usando os comandos:
```bash
sudo docker rm $(sudo docker ps -aq)
sudo docker rmi $(sudo docker images  -q)
```
Continuo com o mesmo problema de **SERVER ERROR**
Mais pessoas obtiveram sucesso??

**Comment by thiagoiferreira** [comment]
Comecei a ter o mesmo problema em ambas as minhas máquinas, o problema surgiu do nada, se eu cancelar todas as alterações que eu fiz ou clonar de novo e o problema continua vindo, tentei resolver mas até o momento não tive nenhum progresso. Estou dependendo de arrumar esse erro pra conseguir trabalhar com o deploy contínuo

**Comment by thiagoiferreira** [comment]
Achei esse tópico após ver que o mongo estava retornando 62 depois de ser executado
https://stackoverflow.com/questions/47850004/mongodb-shutting-down-with-code62
Vou tentar aplicar algumas correções que foram sugeridas dentro desse post e retornarei com os resultados

**Comment by gabrielziegler3** [comment]
Apaguei o repositorio e clonei novamente, aqui a aplicação está funcionando corretamente sem erros no docker na `master`.

![image](https://user-images.githubusercontent.com/18370133/58649999-ff10f800-82e3-11e9-946e-2b0d24b346b2.png)

![image](https://user-images.githubusercontent.com/18370133/58650057-151eb880-82e4-11e9-9b74-75c2cadac214.png)

**Comment by gabrielziegler3** [comment]
Consegui reproduzir o erro ao rodar na máquina virtual da AWS e a partir de agora vou tomar frente dessa issue com o propósito de fechá-la o mais cedo o possível.

**Comment by gabrielziegler3** [comment]
Arrumei o bug do Mongo OpLog. As fontes a seguir foram muito importantes para entender como solucionar esse problema:

- https://rocket.chat/docs/installation/docker-containers/index.html
- https://github.com/RocketChat/Rocket.Chat/issues/14353

**Comment by thiagoiferreira** [comment]
Problema resolvido aqui, bom trabalho!
