### ISSUE TITLE
Make TAP document

### ISSUE THREAD

**Issue by thiagoiferreira** [fga-eps-mds/2019.1-PyLearner#16]
Project Owner to work on project opening term.

**Comment by thiagoiferreira** [comment]
@carlosaragon , please elaborate use checkboxes on the issue to let us know the progress and the topics of which you are working on

**Comment by gabrielziegler3** [comment]
@carlosaragon como está o progresso dessa issue? Não está havendo transparência.

**Comment by carlosaragon** [comment]
Documento concluido e ja disponivel no repositorio.

**Comment by gabrielziegler3** [comment]
tabela da equipe esta quebrada, favor arrumar.
