### ISSUE TITLE
Analise e adições no backlog

### ISSUE THREAD

**Issue by davialvb** [fga-eps-mds/2019.1-PyLearner#163]
# Analise e adições no backlog
---
### Descrição:
Após a ultima reunião de equipe foi visto a necessidade de adições no backlog para melhorias e acrecimos na aplicação.

### Critérios de Aceitação
- [ ] Analise e Novas adições no backlog

**Comment by gabrielziegler3** [comment]
issue descontinuada porque escopo esta fechado
