### ISSUE TITLE
Elicitate Software Requirements

### ISSUE THREAD

**Issue by thiagoiferreira** [fga-eps-mds/2019.1-PyLearner#17]
Elaborate further into the projects software requirements.

**Comment by gabrielziegler3** [comment]
What role exactly should be focusing more on this one?

Also, I believe a questionnaire would be of good use for this task.

**Comment by thiagoiferreira** [comment]
Its best if the whole team worked on it but primarily, I believe it's the PO's job.

**Comment by thiagoiferreira** [comment]
The team elicitated the priority software requirements during the weekly meeting, yet there still hasn't been any specification, this will be deemed as debt for sprint 2

**Comment by thiagoiferreira** [comment]
Dependendo da aplicação e processamento dos resultados do questionário.
Atualmente a quantidade de resultados é insatisfatória, tendo passado mais de uma sprint pra isso e o questionário não foi concluído.

**Comment by gabrielziegler3** [comment]
22 dias desde a criação dessa issue e nenhum update?

**Comment by carlosaragon** [comment]
Os resultados do questionário serão utilizados dentro das limitações do alcance de respostas obtido.

**Comment by gabrielziegler3** [comment]
Nao consigo enxergar mais necessidade e valor nessa issue. Que ponto acham que isso ainda pode nos ajudar no desenvolvimento?

**Comment by thiagoiferreira** [comment]
Estava vendo ela no planejamento e concordo que deva ser descontinuada, a elaboração do backlog e os brainstormings feitos durante a reunião já supriram a necessidade de levantamento de requisitos, já avançamos demais nesse quesito.

**Comment by thiagoiferreira** [comment]
Issue concluída com a criação do documento de requisitos por parte do membro @carlosaragon
