### ISSUE TITLE
Python Training

### ISSUE THREAD

**Issue by thiagoiferreira** [fga-eps-mds/2019.1-PyLearner#18]
* All of the Development team should work on improving their programming skills in Python to prepare for upcoming development
The team member should have proof of their progress in studying python:
- [x] joao15victor08
- [x] ZarathosDeath
- [x] Eugeniosales
- [x] alexportof
- [x] Mexazonic

**Comment by Eugeniosales** [comment]
Short and nice introduction of Python from the TEP's repository.
It begins in the middle of the page.

Link: https://github.com/edsomjr/TEP/blob/master/Introducao/introducao.md

**Comment by alexportof** [comment]
https://www.udemy.com/intro_python/
free Python course in Udemy

**Comment by Mexazonic** [comment]
The follow exercises from URI are very good´s to practice python: 1196, 1566, 1277, 1042, 1062, 1944. Is a good exemple of how to use stack, map and list in yout own context.

**Comment by thiagoiferreira** [comment]
Todos os membros da equipe de desenvolvimento realizaram treinamento em python ao longo da sprint, desta forma a issue foi entregue.
