### ISSUE TITLE
Iniciar Documento de Visão

### ISSUE THREAD

**Issue by thiagoiferreira** [fga-eps-mds/2019.1-PyLearner#19]
A equipe de desenvolvimento deverá criar e desenvolver o documento de visão.
Para aceitação do documento, este deverá conter:
- [x] Introdução
- [x] Posição
- [x] Descrições das partes interessadas
O fechamento desse documento ocorrerá na próxima sprint, entretanto, nesta, deverá haver os pontos de produção definidos e a preparação da equipe para a finalização na próxima sprint

**Comment by gabrielziegler3** [comment]
What is the progress of this document? Is it already being updated to the wiki?

**Comment by joao15victor08** [comment]
https://www.ibm.com/support/knowledgecenter/pt-br/SSWMEQ_4.0.6/com.ibm.rational.rrm.help.doc/topics/r_vision_doc.html
structure of a vision document

**Comment by thiagoiferreira** [comment]
> What is the progress of this document? Is it already being updated to the wiki?

From what was reported yesterday during the daily report, they were studying the structure of the document and how it would be done yet the had not started writing yet, I believe they depend on the requisite elicitation to get going

**Comment by gabrielziegler3** [comment]
Ok, I suggest you upload an initial part of the document to either the wiki or a google docs file to kick it off.

**Comment by thiagoiferreira** [comment]
Tópicos:

1.1 Finalidade [Ernando]

1.3 Definições, Acrônimos e Abreviações [Álex]

1.4 Referências [Álex]

1.5 Visão Geral [Ernando]

3.1 Resumo da Parte Interessada[bruno]

3.3 Ambiente do Usuário [ Eugênio]

3.4 Perfis dos Envolvidos[João Victor]

**Comment by joao15victor08** [comment]
Finalizado o tópico 3.4 Perfis dos Envolvidos

**Comment by thiagoiferreira** [comment]
Boa

**Comment by ZarathosDeath** [comment]
Finalizado os tópicos 1.1- Finalidade e 1.5-Visão Geral

**Comment by Eugeniosales** [comment]
Finalizado o tópico 3.3 - Ambiente de Usuário.

**Comment by thiagoiferreira** [comment]
Documento iniciado, tendo os primeiros três tópicos principais finalizados
