### ISSUE TITLE
Docker Study/Training

### ISSUE THREAD

**Issue by thiagoiferreira** [fga-eps-mds/2019.1-PyLearner#22]
All of the team members must study Docker to some degree, in a way that the whole team would be comfortable with using the technology, meanwhile the Dev-ops must create the docker container for posterior use.
To be deemed complete, this task would have to have all members of the team capable of using a docker container without any issues

**Comment by thiagoiferreira** [comment]
If anyone is interested, I have a Udemy course to recommend on the topic, it touches more complex topics and might be useful for the Dev-ops : 
* https://www.udemy.com/share/1001ESAkMedVtUR34=/

**Comment by Eugeniosales** [comment]
Free Docker Course on Udemy: https://www.udemy.com/docker-essentials/

**Comment by thiagoiferreira** [comment]
Os membros realizaram o treinamento de docker e sabem subir containers.
