### ISSUE TITLE
Attend to GIT training [2]

### ISSUE THREAD

**Issue by gabrielziegler3** [fga-eps-mds/2019.1-PyLearner#24]
We need to have another git training as the activity on branch merging and git workflow was not achieved 100% correctly by all MDS members.

The git activity happens in this [repo](https://github.com/gabrielziegler3/git-test).

Date and time to be decided.

**Comment by gabrielziegler3** [comment]
Git Training [2] will occur on Thursday at noon.

**Comment by gabrielziegler3** [comment]
Correction, Git Training [2] will occur on Saturday among with sprint meetings.

**Comment by thiagoiferreira** [comment]
A equipe de desenvolvimento concluiu o treinamento no dia 30/3, anterior à reunião semanal.
1. Dar clone no repositório: **https://github.com/thiagoiferreira/treinamento-git**
2. Criar nova branch
3. Fazer alguma alteração no documento em alguma linha de código já existente
4. Merjar a branch ‘merjaEssaBranch’
5. Resolver os conflitos apresentados pelo merge
6. Commitar as mudanças do merge/resolução de conflito
7. Dar push nas mudanças para o seu repositório
8. Abrir pull request para a Master
