### ISSUE TITLE
Dockerize the application

### ISSUE THREAD

**Issue by gabrielziegler3** [fga-eps-mds/2019.1-PyLearner#25]
Examine the best options for setting up containers that will run Jupyter Notebook on the browser with the bot.
To be deemed complete, there must be:
- [ ] An initial, functional and usable docker container for development
- [ ] Be adequate for the technologies that are going to be used

**Comment by davialvb** [comment]
See if it helps you:
https://www.dataquest.io/blog/docker-data-science

**Comment by davialvb** [comment]
https://opendreamkit.org/2018/10/17/jupyterhub-docker/

**Comment by gabrielziegler3** [comment]
Jupyter is already working on `docker-compose` on branch [25-dockerize-the-application](https://github.com/fga-eps-mds/2019.1-PyLearner/tree/25-dockerize-the-application).

**Comment by thiagoiferreira** [comment]
Issue aborted, technology scope changed.
