### ISSUE TITLE
Create style code document

### ISSUE THREAD

**Issue by gabrielziegler3** [fga-eps-mds/2019.1-PyLearner#26]
Create the project style code document in which all developers must follow.

**Comment by gabrielziegler3** [comment]
Style guide documented using [PEP 8](https://www.python.org/dev/peps/pep-0008/) at [style-guide](https://github.com/fga-eps-mds/2019.1-PyLearner/wiki/Style-Guide).

**Comment by carlosaragon** [comment]
Style guide is set.
