### ISSUE TITLE
Create Github Pages domain and migrate documentation

### ISSUE THREAD

**Issue by thiagoiferreira** [fga-eps-mds/2019.1-PyLearner#28]
Create a Github pages domain for the projects documentation
This issue will be deemed complete when:
- [x] Domain created and working
- [x] Documentation migrated from integrated wiki to github pages

**Comment by gabrielziegler3** [comment]
[Read the docs](https://readthedocs.org/) might also be a good move.

**Comment by thiagoiferreira** [comment]
Created and migrated the documentation already, closing issue
https://fga-eps-mds.github.io/2019.1-PyLearner/#/docs/Home
