### ISSUE TITLE
Roadmap Individual Tech Leader

### ISSUE THREAD

**Issue by thiagoiferreira** [fga-eps-mds/2019.1-PyLearner#29]
Para que esse issue seja aceita como completa, o Tech Leader deverá elaborar seu roadmap para a
- [x] Release 1
e
- [x] Release 2
Tendo elaborado uma previsão das atribuições da posição ao longo de todas as sprints

**Comment by thiagoiferreira** [comment]
https://github.com/fga-eps-mds/2019.1-PyLearner/commit/af30c6aaf22f1635b97cc84895449622c22104fd

**Comment by gabrielziegler3** [comment]
@all-contributors please add @thiagoiferreira  for docs

**Comment by gabrielziegler3** [comment]
@all-contributors please add @thiagoiferreira for docs

**Comment by gabrielziegler3** [comment]
@all-contributors please add @thiagoiferreira for docs

**Comment by gabrielziegler3** [comment]
@all-contributors please add @thiagoiferreira for docs

**Comment by gabrielziegler3** [comment]
@all-contributors please add @thiagoiferreira for docs

**Comment by gabrielziegler3** [comment]
@all-contributors please add @thiagoiferreira for docs

**Comment by gabrielziegler3** [comment]
FINALLY!!!
