### ISSUE TITLE
Attend to git training

### ISSUE THREAD

**Issue by carlosaragon** [fga-eps-mds/2019.1-PyLearner#3]
* Members of developing team should complete the suggested tutorials that will be available in the following links:
  * https://learngitbranching.js.org
  * https://www.codecademy.com/learn/learn-git 
* All group members should attend to the face-to-face training that will happen 21/03/2019 at 12:00 pm.

**Comment by thiagoiferreira** [comment]
Training was completed by the members and complemented with a dojo on the topic on march 21st from 12pm to 13:30pm

**Comment by gabrielziegler3** [comment]
Git training complete within **two** hours.

* who attended the training:  
@Mexazonic @gabrielziegler3 @thiagoiferreira @davialvb @joao15victor08 @Eugeniosales @ZarathosDeath @alexportof 

* who missed it: @carlosaragon
