### ISSUE TITLE
Roadmap Individual DevOps

### ISSUE THREAD

**Issue by thiagoiferreira** [fga-eps-mds/2019.1-PyLearner#30]
Para que esse issue seja aceita como completa, o DevOps deverá elaborar seu roadmap para as:
- [ ] Release 1
e
- [ ] Release 2
Tendo elaborado uma previsão das atribuições da posição ao longo de todas as sprints.

**Comment by gabrielziegler3** [comment]
- [Roadmap DevOps](https://github.com/fga-eps-mds/2019.1-PyLearner/blob/ed677da57208c2b6a22bc4bc563662dbee6a25d5/docs/Roadmap-DevOps.md) finalizado.

**Comment by carlosaragon** [comment]
Roadmap finalizado.
