### ISSUE TITLE
Roadmap Individual Arquiteto

### ISSUE THREAD

**Issue by thiagoiferreira** [fga-eps-mds/2019.1-PyLearner#32]
Para que esse issue seja aceita como completa, o Arquiteto deverá elaborar seu roadmap para a
- [ ] **Release 1**
- [ ] **Release 2**

Tendo elaborado uma previsão das atribuições da posição ao longo de todas as sprints.

**Comment by davialvb** [comment]
Roadmap adicionado aos docs.

**Comment by thiagoiferreira** [comment]
Por favor adicione o documento ao documento _sidebar.md para que seja acessível pelo github pages, feito isso pode fechar a issue

**Comment by gabrielziegler3** [comment]
Corrigido e aceito!
