### ISSUE TITLE
Levantar perguntas para o questionário do produto

### ISSUE THREAD

**Issue by thiagoiferreira** [fga-eps-mds/2019.1-PyLearner#33]
### Objetivo
Esta issue consiste no levantamento de perguntas, onde, estas serão repassadas num questionário destinado ao possível público alvo do produto: Possíveis Programadores Iniciantes em Machine Learning.
### Meio de alcançar o objetivo
Nesta issue é fundamental a participação de toda a equipe, tanto de desenvolvimento quanto de gerência para que possamos atingir a melhor qualidade possível no questionário.
### Completude
Para que seja dada como completa, deverão ser selecionadas ao menos 6 perguntas que foram levantadas nos comentários pela equipe.

**Comment by carlosaragon** [comment]
"Você ja teve algum tipo de contato com ml?"
(Se sim)
 "Qual a etapa que foi mais dificil para você?"

**Comment by ZarathosDeath** [comment]
"Você acha que seria de ajuda ter um chatbot para tirar suas dúvidas de imediato sobre exercícios? "
"Quais as maiores dificuldades você considera que te atrapalham na hora de resolver um exercicio ?"
"Você acha mais importante ter uma aula guiada ou que tenha um bot onde você possa tirar dúvidas a qualquer momento?"

**Comment by Mexazonic** [comment]
"Você considera viável o bot conceder dicas para facilitar a aprendizagem após algumas tentativas?"
"Você costuma anotar as novas informações adquiridas durante o processo de aprendizado?"
"Realizaria uma "prova final" para testar seus novos conhecimentos em cada etapa?"

**Comment by Eugeniosales** [comment]
"Quais assuntos de Ml, você considera mais difíceis de serem esclarecidos com ajuda de um Bot?"
"Quais elementos você considera indispensáveis para um Bot esclarecer suas dúvidas?"
"Em uma escala de 0 à 10, como você avalia o modelo de aprendizagem proposto?"

**Comment by thiagoiferreira** [comment]
"O que um chatbot orientado a ensino precisaria ter para que você considere usa-lo?"
"Em termos de personalidade de chatbot, você gostaria que esse tivesse uma ou não"(Acho que precisa reformular pra uma maneira melhor de perguntar mas é isto)
"Se sim para a resposta acima, que tipo de personalidade você acha que o bot deveria ter?" (Resposta Textual)
"Você consideraria usar um chatbot em seu ambiente local caso esse necessitasse de configuração prévia (download)?"
"E se esse fosse integrado à uma ferramenta que você já utilizasse?"

**Comment by carlosaragon** [comment]
Boa participação pessoal! O questionario com as perguntas consideradas mais relevante vai estar disponivel na quinta-feira.
