### ISSUE TITLE
Aplicar Questionário para o Público

### ISSUE THREAD

**Issue by thiagoiferreira** [fga-eps-mds/2019.1-PyLearner#34]
### Criação do Questionário
O questionário em questão deve ser criado pelo Product Owner na ferramenta de preferência deste, utilizando as perguntas levantadas na [Issue#33](https://github.com/fga-eps-mds/2019.1-PyLearner/issues/33)
### Divulgação do Questionário
Toda a equipe deverá auxiliar o PO na divulgação do questionário, utilizando redes sociais e outros meios relevantes.
### Aceitação da coleta
Para que o esta issue seja aceita como completa, o questionário deve ter, no mínimo 50 respostas até o final da sprint, tendo como preferencia um valor de duas a três vezes o mínimo.

#### Para acompanhamento de progresso, conforme a progressão das fases, devem ser preenchidas as caixas abaixo:
- [x] Criação do questionário completa
- [x] Divulgação do questionário completa
- [ ] Quantidade mínima de respostas obtidas
- [ ] Quantidade desejada de respostas obtidas

**Comment by carlosaragon** [comment]
Pessoal o formulário versão inicial esta aqui, comentem o que vocês acharam.
https://drive.google.com/open?id=1IjL9VgxkwD3yqxmmDud2Q-xXLKjNcVTFgewzKrQ1gXM

**Comment by Eugeniosales** [comment]
Está Ok.

**Comment by carlosaragon** [comment]
Então podem divulgar nos grupos de vocês, para o maior número de pessoas responder!

**Comment by carlosaragon** [comment]
Pessoal precisamos divulgar mais, só tivemos 10 respostas até o momento!

**Comment by carlosaragon** [comment]
Devido ao numero restrito de respostas e o atraso na divulgação do questionário, serão utilizados somente os dados coletados até o momento dando a devida relevância aos resultados.
