### ISSUE TITLE
Processar informações obtidas através da aplicação do questionário	

### ISSUE THREAD

**Issue by thiagoiferreira** [fga-eps-mds/2019.1-PyLearner#35]
### Objetivo
Após coletadas as amostras oriundas da aplicação do questionário da [issue#34](https://github.com/fga-eps-mds/2019.1-PyLearner/issues/34), o PO deve produzir um artefato através dos dados coletados, que agregue algo para o produto em si.
### Aceitação
- [x] Artefato para processamento das informações produzido

**Comment by carlosaragon** [comment]
Pessoal o formulário versão inicial esta aqui, comentem o que vocês acharam.
https://drive.google.com/open?id=1IjL9VgxkwD3yqxmmDud2Q-xXLKjNcVTFgewzKrQ1gXM

**Comment by carlosaragon** [comment]
Não foi obtida uma quantidade mínima de respostas para a confecção do doc ainda.

**Comment by carlosaragon** [comment]
Segue em anexo o resultado das respostas obtidas. 
https://drive.google.com/file/d/1J7SkvkJJFzhoPZKrHtoBv4viz-rMin8z/view?usp=sharing
