### ISSUE TITLE
Criação protótipos de baixa fidelidade

### ISSUE THREAD

**Issue by thiagoiferreira** [fga-eps-mds/2019.1-PyLearner#38]
### Objetivo
Criação de protótipos correspondentes às páginas planejadas a priori para a aplicação. Subindo-os num artefato de documentação dos protótipos.

### Aceitação
- [x] Página principal da aplicação.

Edit: O Protótipo de baixa fidelidade para visualização ampliada do Chatbot foi removida dos requisitos e repassada como necessidade apenas para o protótipo de alta fidelidade

**Comment by gabrielziegler3** [comment]
Não entendi os critérios. Landing não é a a página principal? Chabot desacoplado? Não foi decidido que seria feito na sidebar?

**Comment by gabrielziegler3** [comment]
Issue atualizada. Dúvidas resolvidas.

**Comment by gabrielziegler3** [comment]
# prototipo de baixa fidelidade do sistema
![prototipo_baixa_finalidade](https://user-images.githubusercontent.com/18370133/55503018-2b7e0000-5624-11e9-8125-ff761fe91cee.png)

**Comment by thiagoiferreira** [comment]
Bom protótipo da página principal da aplicação, bem próximo do que havia sido idealizado.
Protótipo Aceito, suba uma página na branch gh-pages e coloque o link na sidebar

**Comment by gabrielziegler3** [comment]
@all-contributors please add @gabrielziegler3 for docs
