### ISSUE TITLE
Documento de Visão tópico 4: Visão Geral do Produto

### ISSUE THREAD

**Issue by thiagoiferreira** [fga-eps-mds/2019.1-PyLearner#39]
### Objetivo
Desenvolver o tópico 4 do documento de visão, para eventual término do documento.
### Aceitação
Para aceitação, este tópico deverá contar com os seguintes subtópicos escritos:
 - [x] 4.1 Perspectiva do Produto
 - [x] 4.2 Resumo dos recursos

**Comment by alexportof** [comment]
Vou fazer a 4.1 e o Ernando a 4.2

**Comment by ZarathosDeath** [comment]
Finalizado o tópico 4 do Documento de visão e enviado para revisão

**Comment by gabrielziegler3** [comment]
Tópicos avaliados e aceitos.
