### ISSUE TITLE
Come up with a name for the project

### ISSUE THREAD

**Issue by gabrielziegler3** [fga-eps-mds/2019.1-PyLearner#4]
The project consists of a chatbot that will help fellow programmers how to program on a specific context (it could be a programming paradigm, programming principles, data structures concepts, etc). 

* How shall we name our robot teacher?

**Comment by thiagoiferreira** [comment]
codeNoobot

**Comment by davialvb** [comment]
BotHelpsML

**Comment by thiagoiferreira** [comment]
<i><h3>MachLearner</h3></i>
Mach as in Machine and the measurement of speed of sound, related to making the learning experience in machine learning faster and the Learner gives sort of and identity or a personification if preferred, to the bot.

**Comment by davialvb** [comment]
**Pyter-Learn**
pyter referring to jupyter notebook... Maybe later we can think of making a mascot with the "pyter" name.

**Comment by Mexazonic** [comment]
Botine Learning

**Comment by gabrielziegler3** [comment]
**PyLearner** short and self-explainable.

**Comment by Eugeniosales** [comment]
**PyBot** 
short and straightforward as well.

**Comment by carlosaragon** [comment]
The team chooses Pyter-Learn as the products name.
