### ISSUE TITLE
Documento de Visão tópico 5: Recursos do Produto

### ISSUE THREAD

**Issue by thiagoiferreira** [fga-eps-mds/2019.1-PyLearner#40]
### Objetivo
Desenvolver o tópico 5 do documento de visão, para eventual término do documento. Nestes tópicos, o atuante deve fazer um levantamento dos recursos definidos pela equipe, que farão parte do produto.
### Aceitação
Para aceitação, este tópico deverá contar com o subtópicos definidos pelo escritor do documento, pois faz parte do trabalho, entretanto, para ser entregue, será feita uma revisão que analisará a completude do tópico.
- [x] Recursos levantados e desenvolvidos
- [x] Documento Revisado

**Comment by Eugeniosales** [comment]
Finalizado o tópico 5 do documento de visão e enviado para a revisão.

**Comment by gabrielziegler3** [comment]
Tópico revisado e aceito.

**Comment by gabrielziegler3** [comment]
@all-contributors please add @Eugeniosales  for docs

**Comment by gabrielziegler3** [comment]
@all-contributors please add @Eugeniosales for docs
