### ISSUE TITLE
Documento de Visão tópico 6: Restrições

### ISSUE THREAD

**Issue by thiagoiferreira** [fga-eps-mds/2019.1-PyLearner#41]
### Objetivo
Desenvolver o tópico 6 do documento de visão, referente às restrições enfrentadas pelo produto de software a ser desenvolvido.

### Aceitação
Para aceitação, este tópico deverá contar com os subtópicos referentes as restrições, definidas pelo escritor do documento. Entretanto, para aceitação, será feita uma revisão que analisará a completude do tópico.
- [x] Restrições levantadas e desenvolvidos
- [x] Documento Revisado

**Comment by gabrielziegler3** [comment]
### Minha opinião:

* Acho que os itens listados não estão muito condizentes com o tópico **restrições** do documento de visão. Dê uma olhada em um [exemplo](https://github.com/fga-eps-mds/2018.1-Reabilitacao-Motora/blob/development/docs/wiki/Documento-de-Vis%C3%A3o.md#6-restri%C3%A7%C3%B5es) que possa ficar mais claro a função deste tópico.
* erro de digitação: "PyLearnner"

**Comment by Mexazonic** [comment]
Tópico revisado e enviado para uma nova análise.

**Comment by gabrielziegler3** [comment]
Revisoes aceitas

**Comment by gabrielziegler3** [comment]
@all-contributors please add @Mexazonic  for docs
