### ISSUE TITLE
Documento de Arquitetura tópico 1: Introdução

### ISSUE THREAD

**Issue by thiagoiferreira** [fga-eps-mds/2019.1-PyLearner#43]
### Objetivo
Desenvolver o tópico 1 do documento de Arquitetura, referente à Introdução do documento
### Aceitação
Para aceitação este fragmento do documento deverá conter:
 - [ ] Finalidade
 - [ ] Escopo
 - [ ] Definições, Acrônimos e Abreviações
 - [ ] Referências

**Comment by thiagoiferreira** [comment]
Recomendo que façam este tópico após completar todos os outros tópicos do documento de arquitetura

**Comment by gabrielziegler3** [comment]
@all-contributors please add @alexportof for docs
