### ISSUE TITLE
Documento de Arquitetura tópico 2: Representação da Arquitetura

### ISSUE THREAD

**Issue by thiagoiferreira** [fga-eps-mds/2019.1-PyLearner#44]
### Objetivo
Desenvolver o tópico 2 do documento de Arquitetura, referente à Representação da Arquitetura, neste sendo especificadas as tecnologias utilizadas no projeto e sua especificação arquitetural. 
### Aceitação
Para aceitação este fragmento do documento deverá conter:
 - [ ] Tecnologias
 - [ ] Diagramas de Representação Arquitetural para cada tecnologia

**Comment by davialvb** [comment]
Tópico 2 foi iniciado, ficara faltando apenas a explicação dos microserviços que vão ser adicionados após o levantamento dos requisitos/funcionalidades extraidos do questionario feito e analizado pelo PO @carlosaragon .
