### ISSUE TITLE
Documento de Arquitetura tópico 3: Metas e Restrições de Arquitetura

### ISSUE THREAD

**Issue by thiagoiferreira** [fga-eps-mds/2019.1-PyLearner#45]
### Objetivo
Desenvolver o tópico 3 do documento de Arquitetura, referente à Metas e Restrições de Arquitetura.
### Aceitação
Para aceitação este fragmento do documento deverá conter especificado:
- [ ] Metas e Restrições de Arquitetura

**Comment by gabrielziegler3** [comment]
@all-contributors please add @ZarathosDeath  for docs
