### ISSUE TITLE
Há a necessidade do nosso sistema ter um back-end?

### ISSUE THREAD

**Issue by gabrielziegler3** [fga-eps-mds/2019.1-PyLearner#46]
### Dúvida

Depois de termos definido uma visão macro da arquitetura fiquei com o questionamento de se era realmente necessário a criação de um back-end. Não consegui visualizar a sua funcionalidade e finalidade. O que acham? Alguém vê uma finalidade clara ou seria mais um elefante branco?

Qual a opinião do time e do arquiteto @davialvb?

**Comment by gabrielziegler3** [comment]
Aparentemente há, analisei algumas arquiteturas e tirei dúvidas com membros do Lappis que trabalham em desenvolvimento de chatbots.

- um exemplo de arquitetura utilizado é o seguinte:

![image](https://user-images.githubusercontent.com/18370133/55422998-5e0bf800-5553-11e9-975c-4542e6f54e9c.png)

**Comment by thiagoiferreira** [comment]
boa
