### ISSUE TITLE
Documento de Visão tópico 2: Posição

### ISSUE THREAD

**Issue by thiagoiferreira** [fga-eps-mds/2019.1-PyLearner#47]
### Objetivo
Desenvolver o tópico 2 do documento de visão, para eventual término do documento.
### Aceitação
Para aceitação, este tópico deverá contar com os seguintes subtópicos escritos:
- [x] Oportunidade de Negócios
- [x] Instrução do Problema
- [x] Instrução de Posição do Produto

**Comment by joao15victor08** [comment]
Finalizado o tópico 2 Posição

**Comment by thiagoiferreira** [comment]
Erro de digitação no tópico 2.2

**Comment by gabrielziegler3** [comment]
não use expressões muito sensacionalistas ou vagas como:

- não existe um local para tirar dúvidas rápidas ou mais expecíficas sobre ML. (Certeza que não existe nenhum recurso para dúvidas específicas de ML? Acho que existem sim, hein).
- concentra tudo em uma única aplicação. (Concentra tudo o que? Defina o que a aplicação vai se propor claramente).

**Comment by gabrielziegler3** [comment]
erro de digitação corrigido e termos vagos [corrigidos](https://fga-eps-mds.github.io/2019.1-PyLearner/#/docs/documentation/Documento-de-Visao?id=_2-posi%C3%A7%C3%A3o), issue aceita!

**Comment by gabrielziegler3** [comment]
@all-contributors please add @joao15victor08 for docs
