### ISSUE TITLE
Documento de Arquitetura tópico 4: Visão Lógica

### ISSUE THREAD

**Issue by thiagoiferreira** [fga-eps-mds/2019.1-PyLearner#48]
### Objetivo
Desenvolver o tópico 4 do documento de Arquitetura, referente à Visão Lógica, contendo a visão geral e a estruturação dos módulos de desenvolvimento a serem utilizados
### Aceitação
Para aceitação este fragmento do documento deverá conter:
- Diagrama de Pacotes para:
 - [ ] Front-end
 - [ ] Back-end

**Comment by Eugeniosales** [comment]
Tópico 4: Diagrama de Pacotes para Backend adicionado para revisão.
