### ISSUE TITLE
Learn about microservices architecture

### ISSUE THREAD

**Issue by carlosaragon** [fga-eps-mds/2019.1-PyLearner#5]
* All group members should read the following articles to learn more about microservices architecture:
  - https://opensource.com/resources/what-are-microservices
  - https://dzone.com/articles/what-is-microservices-an-introduction-to-microserv
  - https://hackernoon.com/an-introduction-to-microservice-based-architecture-through-story-part-1-55c553ac4bd9

**Comment by davialvb** [comment]
this link is more related to our theme:
https://blog.craftworkz.co/creating-a-highly-scalable-chatbot-in-a-microservices-architecture-using-ibm-bluemix-15164a9b03da

**Comment by gabrielziegler3** [comment]
This repo brings a demo. 
https://github.com/microservices-demo/microservices-demo

**Comment by davialvb** [comment]
Após o estudo sobre os microserviços foi gerado um documento para melhor apresentar o que foi aprendido. Ele se encontra na pasta docs. 
[Documento sobre microserviços](https://github.com/fga-eps-mds/2019.1-PyLearner/blob/master/docs/doc_microservices.md)

**Comment by thiagoiferreira** [comment]
Os resultados da pesquisa foram compartilhados com a equipe, aumento em geral o conhecimento dos membros sobre micro serviços e decisões quanto à arquitetura foram tomadas.
