### ISSUE TITLE
Treinamento RASA

### ISSUE THREAD

**Issue by thiagoiferreira** [fga-eps-mds/2019.1-PyLearner#50]
## Objetivo
Arquiteto dar um treinamento/dojo com a equipe de desenvolvimento para que essa obtenha mais familiaridade com o RASA.
## Aceitação
- [x] Treinamento dado

**Comment by davialvb** [comment]
## Treinamento de RASA realizado.

Presentes: @Eugeniosales , @Mexazonic , @alexportof, @gabrielziegler3, @thiagoiferreira 

### Topicos:
* Rasa NLU:
    Como preparar o dado.
    Funcionamento da pipeline e o que usar.
    Como treinar o modelo.
    Como vizualizar e validar os resultados obtidos.
