### ISSUE TITLE
Protótipo de Alta fidelidade

### ISSUE THREAD

**Issue by thiagoiferreira** [fga-eps-mds/2019.1-PyLearner#51]
## Objetivo
Criar um protótipo em que seja representado o front-end do projeto de forma detalhada para embasamento durante o desenvolvimento.
## Aceitação
- [x] Protótipo Homepage
- [x] Protótipo página de desenvolvimento

**Comment by thiagoiferreira** [comment]
A issue não foi entregue no decorrer da sprint 3, esta será dada como débito para a sprint 4.
A priori os membros que irão trabalhar nesta serão mantidos.

**Comment by carlosaragon** [comment]
Tem algum lugar onde o resto da equipe pode acompanhar o andamento do protótipo?

**Comment by thiagoiferreira** [comment]
O desenvolvimento do protótipo foi postergado para a sprint 6, antes da release 1, o membro @ZarathosDeath será o único responsável, a partir desta, pelo débito

**Comment by ZarathosDeath** [comment]
Protótipo finalizado e enviado para revisão

**Comment by thiagoiferreira** [comment]
Protótipo revisado
