### ISSUE TITLE
Learn about chatbot

### ISSUE THREAD

**Issue by carlosaragon** [fga-eps-mds/2019.1-PyLearner#6]
* All group members should take the following online course to have an idea about how to build a chatbot:
  - https://www.datacamp.com/courses/building-chatbots-in-python?utm_source=adwords_ppc&utm_campaignid=1658343524&utm_adgroupid=63833880935&utm_device=c&utm_keyword=%2Bmake%20%2Bchatbot&utm_matchtype=b&utm_network=g&utm_adpostion=1t2&utm_creative=319519154391&utm_targetid=aud-522010995285:kwd-306348838227&utm_loc_interest_ms=&utm_loc_physical_ms=1001541&gclid=CjwKCAjwycfkBRAFEiwAnLX5Iea3ONevtQwrqKGrk0FyFpB6lQlXnUcu-qXuR9fEM9qymx3Eo1rluhoCYS4QAvD_BwE

**Comment by davialvb** [comment]
See these tools.
https://azure.microsoft.com/en-us/services/bot-service
https://rasa.com/

**Comment by thiagoiferreira** [comment]
As pesquisas a respeito do chatbot foram realizadas pelo arquiteto e ajudaram na tomada de decisões quanto ao rumo do projeto.
