### ISSUE TITLE
TS 22 - Preparar dados de treino

### ISSUE THREAD

**Issue by carlosaragon** [fga-eps-mds/2019.1-PyLearner#65]
# TS 22 - Preparar dados de treino
---
### Descrição:
Preparar os arquivos de treino do chatbot relativos ao módulo de interação. Modulo responsável por mensagens e respostas de saudação do bot.

### Critérios de Aceitação
- [x] O arquivo de treino deve estar corretamente formatado para treinamento do bot.
- [x] Os dados de treino devem estar em português.

### Tarefas
- [x] Criar intenções.
- [x] Criar cenarios.

**Comment by thiagoiferreira** [comment]
Código Revisado no fechamento da sprint, PR virá com o término da outra dependência
