### ISSUE TITLE
Criar ambiente docker para jupyter

### ISSUE THREAD

**Issue by gabrielziegler3** [fga-eps-mds/2019.1-PyLearner#67]
- [x] Ambiente subindo jupyter para acesso local.

**Comment by gabrielziegler3** [comment]
Docker subindo `jupyter notebook` criado [#9059cf](https://github.com/pylearner-bot/pylearner-rasa/commit/9059cf3cc032f05571e8e03ab64b58e50600e9ea)

**Comment by thiagoiferreira** [comment]
Docker funcionando corretamente, PR revisado e merjado, fechando issue
