### ISSUE TITLE
Criar ambiente docker para o Rocketchat

### ISSUE THREAD

**Issue by gabrielziegler3** [fga-eps-mds/2019.1-PyLearner#68]
- [x] Ambiente subindo o serviço do Rocketchat.

**Comment by gabrielziegler3** [comment]
Servico adicionado em [ae5faac](https://github.com/pylearner-bot/pylearner-rasa/commit/ae5faac053f0e8eff39d59b129bedb0cf7807d68).

**Comment by thiagoiferreira** [comment]
Ambiente funcional, issue aceita no fechamento da sprint
