### ISSUE TITLE
Criar ambiente docker para o db

### ISSUE THREAD

**Issue by gabrielziegler3** [fga-eps-mds/2019.1-PyLearner#69]
- [x] Docker subindo serviço do Mongo DB para consumo do chatbot.

**Comment by gabrielziegler3** [comment]
Servico do Mongo DB subindo [#8db7ee](https://github.com/pylearner-bot/pylearner-rasa/commit/8db7ee6c184534c516fea7325b1e4b633caf3801)

**Comment by thiagoiferreira** [comment]
Docker funcionando corretamente, PR revisado e merjado, fechando issue
