### ISSUE TITLE
Decide which topic the bot will help with

### ISSUE THREAD

**Issue by gabrielziegler3** [fga-eps-mds/2019.1-PyLearner#7]
What topics should our bot help with? i.e. Machine Learning, C lang, Python lang, object-oriented programming (OOP), JS...

**Comment by Eugeniosales** [comment]
Machine learning would be interesting for the first option and python afterwards.

**Comment by Mexazonic** [comment]
Machine Learning as first choice and C as secondary choice.

**Comment by gabrielziegler3** [comment]
Agreed Machine Learning would be a hot topic as it is trending on new students now. Let's wait for the majority to vote and we can close this issue.

**Comment by ZarathosDeath** [comment]
I vote for Machine Learning, I think could be really interesting project and be used a lot, since it's a trending topic and a emerging tecnology. There is a course in FGA for Machine Learning using C language, too. But I would say we could use another programming language, such as Python.

**Comment by thiagoiferreira** [comment]
I believe that C or another programming language that would be focused on non-experienced programmers would be a better choice instead of machine learning. Students that are learning machine learning in most cases already have an intermediate level in programming and know how to do research much better and efficiently than initiates, and due to this, wouldn't have a large need for a chatbot concerning the topic.
Another thing that should be taken in concern is the fact that most of the dev team have little to no knowledge concerning the topic of machine learning as of this moment, of course you guys will learn eventually but that might be a large risk that must be taken into account this early on in the project.

**Comment by davialvb** [comment]
Maybe "C" is the best choice!

**Comment by gabrielziegler3** [comment]
> I believe that C or another programming language that would be focused on non-experienced programmers would be a better choice instead of machine learning. Students that are learning machine learning in most cases already have an intermediate level in programming and know how to do research much better and efficiently than initiates, and due to this, wouldn't have a large need for a chatbot concerning the topic.
> Another thing that should be taken in concern is the fact that most of the dev team have little to no knowledge concerning the topic of machine learning as of this moment, of course you guys will learn eventually but that might be a large risk that must be taken into account this early on in the project.

I agree this may increase the risk compared to just teaching C lang, but we have to take into account that we are going to be "competing" with other groups with the same objective. Choosing an obvious topic to teach also implicates in some risks as it would mean a bigger responsibility.

**Comment by carlosaragon** [comment]
I agree that machine learning is a hot topic and i believe the group has more knowledge about this topic.

**Comment by thiagoiferreira** [comment]
Considering the other groups would likely want to use 'C', we could consider trying Python, Javascript or another language that could be used to teach beginners, maybe even try to attack topics like Object Oriented Programming. Doing that would be more accessible and be still be useful towards beginners.

**Comment by davialvb** [comment]
I'm ok with machine learning too.

**Comment by gabrielziegler3** [comment]
Issue closed and the topic will be: **Machine Learning**

* Pro Machine Learning: **6**
* Against: **1**
* Hasn't voted: @joao15victor08, @alexportof
