### ISSUE TITLE
Bug no docker com rocket.chat

### ISSUE THREAD

**Issue by ZarathosDeath** [fga-eps-mds/2019.1-PyLearner#70]
* **Estou enviando um ...**
  - [x] Bug
  - [ ] Requisição de nova funcionalidade
  - [ ] Necessitando suporte

* **Você quer requisitar uma *feature* ou reportar um *bug*?**
bug

* **Qual o comportamento atual?**
No jupyter notebook não aparece a box do rocket.chat, apesar de o servidor do rocket.chat estar funcionando

* **Qual o comportamento esperado?**
Deveria carregar o a box do rocket.chat no jupyter notebook

* **Qual é o caso de motivação / uso para mudar o comportamento?**
correção de bug

* **Por favor, conte-nos sobre o seu ambiente:**

    Python: 3.6.7 </br>
    Versão: y x.y.z </br>
    Alguma coisa importante: Modelo W </br>

* **Outras Informações**

**Comment by carlosaragon** [comment]
Aprece que o bug foi corrigido corretamente.
