### ISSUE TITLE
Criar de uma identidade visual para a aplicação

### ISSUE THREAD

**Issue by davialvb** [fga-eps-mds/2019.1-PyLearner#71]
- [x] Criação de uma identidade visual

**Comment by Eugeniosales** [comment]
![Pylearner_logo_neural](https://user-images.githubusercontent.com/42457772/56076468-fdc55380-5da7-11e9-956b-4b7c249e8a24.png)

**Comment by Eugeniosales** [comment]
![Pylearner_logo_neural_2](https://user-images.githubusercontent.com/42457772/56076479-12095080-5da8-11e9-8c8e-0e15b69ef7d6.png)

**Comment by Eugeniosales** [comment]
![Pylearner_logo_neural_Sem_fonte](https://user-images.githubusercontent.com/42457772/56076490-382ef080-5da8-11e9-9c94-261366378cc9.png)

**Comment by Eugeniosales** [comment]
Opções de logo para representar o bot do projeto para serem vortados.

**Comment by thiagoiferreira** [comment]
Ídolo, bom trabalho

**Comment by thiagoiferreira** [comment]
1a alternativa aceita pela equipe, fechando issue.
