### ISSUE TITLE
Refatorar o Backlog

### ISSUE THREAD

**Issue by gabrielziegler3** [fga-eps-mds/2019.1-PyLearner#73]
- [x] Épicos bem definidos com clareza e entendimento das US associadas.
- [x] Priorização adequada as US usando [MoSCoW](https://www.agilebusiness.org/content/moscow-prioritisation)

**Comment by gabrielziegler3** [comment]
[Documento](https://github.com/fga-eps-mds/2019.1-PyLearner/blob/master/docs/Backlog.md) finalizado.

**Comment by carlosaragon** [comment]
Qual o link para o documento?

**Comment by davialvb** [comment]
Não entendi o assign depois da issue fechada.
