### ISSUE TITLE
Mover documtação para ReadTheDocs

### ISSUE THREAD

**Issue by gabrielziegler3** [fga-eps-mds/2019.1-PyLearner#74]
- [x] todos documentos linkados corretamente.

**Comment by thiagoiferreira** [comment]
Vou tentar mover a documentação amanhã quando eu for subir os documentos da sprint, acredito que a documentação toda já está lá, só é necessário colocá-los na barra de navegação, correto?

**Comment by davialvb** [comment]
Exato, está faltando apenas linkar de acordo com o documento.

**Comment by davialvb** [comment]
[Documentos](https://fga-eps-mds.github.io/2019.1-PyLearner/) adicionados, verifique se falta algum importante que não está lá.

**Comment by gabrielziegler3** [comment]
Estão faltando todos os documentos de polítcas do projeto. Além disso há muita duplicidade de documentos ainda. Acho que tem que ter maior clareza nos paths desses documentos, existem 3 pastas com nome similar a documento: docs, documents e documentation.
