### ISSUE TITLE
US01 - Eu como usuário desejo saber como importar dados de um CSV

### ISSUE THREAD

**Issue by thiagoiferreira** [fga-eps-mds/2019.1-PyLearner#75]
# US01 - Eu como usuário desejo saber como importar dados de um CSV
---
### Descrição:
Nessa história de usuário o desenvolvedor deverá preparar o código para o treinamento do bot no tópico de importação de dados, visando especificamente a importação de dados em CSV.
O desenvolvedor deverá produzir um artefato de documentação com um workflow de como aquilo que ele está fazendo para o bot funciona, criar os intents baseado nisso, os cenários baseado nos intents e então treinar o modelo

### Critérios de Aceitação
Para a aceitação desta história, a entrega deve cumprir os seguintes critérios de aceitação:
- [x] Todo o dialogo do bot deve estar em português.
- [x] As respostas devem ser escritas de forma compreensível ao usuário.
- [x] As respostas do bot devem ser funcionais e corretas de forma que o usuário seja capaz de usar a informação recebida sem problemas.

### Tarefas
Para a aceitação desta história, deve ter as seguintes tasks constituintes concluídas:
- [x] [Documentação de Estudo do tema](https://github.com/fga-eps-mds/2019.1-PyLearner/issues/82)
- [x] [Intents Criados](https://github.com/fga-eps-mds/2019.1-PyLearner/issues/88)
- [x] [Cenários/Histórias criadas](https://github.com/fga-eps-mds/2019.1-PyLearner/issues/99)
- [ ] [Modelo treinado](https://github.com/fga-eps-mds/2019.1-PyLearner/issues/104)

**Comment by davialvb** [comment]
Dei uma olhada na documentação criada, adicione outras formas de abrir o arquivo como por exemplo o <b>Pandas</b>. E os parametros possiveis que podem ser passados ao abrir esse arquivo.

**Comment by alexportof** [comment]
Acha que adicionar mais um tópico explicando sobre o Pandas e um exemplo de como ler um arquivo csv por meio dele ta bom?

**Comment by davialvb** [comment]
Não precisa explicar o <b>pandas</b> como um todo, dei ele como exemplo por ele ter um read_csv interessante. Um ótimo [link](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html) para ter como base. Lá tem tudo que precisa, até explicações dos parametros.

**Comment by alexportof** [comment]
Fiz as alterações,link[https://github.com/fga-eps-mds/2019.1-PyLearner/blob/master/docs/Documento-da-US01.md]

**Comment by alexportof** [comment]
Fiz as [alterações](https://github.com/fga-eps-mds/2019.1-PyLearner/blob/master/docs/Documento-da-US01.md)

**Comment by davialvb** [comment]
Não é necessario o modelo treinado como tarefa. Está aceita.
