### ISSUE TITLE
US15 - Eu como usuário desejo saber como visualizar o histograma das features

### ISSUE THREAD

**Issue by thiagoiferreira** [fga-eps-mds/2019.1-PyLearner#79]
# US15 - Eu como usuário desejo saber como visualizar o histograma das features 
---
### Descrição:
Nessa história de usuário o desenvolvedor deverá preparar o código para o treinamento do bot no tópico de criação de um histograma, de forma que o usuário possa descobrir o balanceamento das features do dataset. 
O desenvolvedor deverá produzir um artefato de documentação com um workflow de como aquilo que ele está fazendo para o bot funciona, criar os intents baseado nisso, os cenários baseado nos intents e então treinar o modelo.

### Critérios de Aceitação
Para a aceitação desta história, a entrega deve cumprir os seguintes critérios de aceitação:
- [x] Todo o dialogo do bot deve estar em português.
- [x] As respostas devem ser escritas de forma compreensível ao usuário.
- [x] As respostas do bot devem ser funcionais e corretas de forma que o usuário seja capaz de usar a informação recebida sem problemas.

### Tarefas
Para a aceitação desta história, deve ter as seguintes tasks constituintes concluídas:
- [x] [Documentação de Estudo do tema](https://github.com/fga-eps-mds/2019.1-PyLearner/issues/86)
- [x] [Intents Criados](https://github.com/fga-eps-mds/2019.1-PyLearner/issues/92)
- [x] [Cenários/Histórias criadas](https://github.com/fga-eps-mds/2019.1-PyLearner/issues/103)
- [ ] [Modelo treinado](https://github.com/fga-eps-mds/2019.1-PyLearner/issues/104)

**Comment by davialvb** [comment]
Não é necessario o modelo treinado como tarefa. Está aceita.
