### ISSUE TITLE
Create Pull Request Template

### ISSUE THREAD

**Issue by thiagoiferreira** [fga-eps-mds/2019.1-PyLearner#8]
- [x] Add a Pull Request Template to the repository  for adequating it to github's  recommended community standards

https://help.github.com/en/articles/creating-a-pull-request-template-for-your-repository

**Comment by davialvb** [comment]
[Pull Request Template](https://github.com/fga-eps-mds/2019.1-Grupo-10/blob/master/.github/PULL_REQUEST_TEMPLATE.md) created.
