### ISSUE TITLE
Arrumar hyperlinks nos documentos

### ISSUE THREAD

**Issue by gabrielziegler3** [fga-eps-mds/2019.1-PyLearner#81]
Alguns hyperlinks foram quebrados quando migrou a documentacao para ReadTheDocs.
- [x] todos hyperlinks consertados.
- [x] todas imagens aparecendo normalmente.

**Comment by davialvb** [comment]
[Hyperlinks](https://fga-eps-mds.github.io/2019.1-PyLearner/) arrumados!

**Comment by gabrielziegler3** [comment]
Secao `contributors` esta bugada e as imagens dos README continuam quebradas. Além disso há uma sobreposição do botão de expandir com o nome da aba na sidebar que precisa ser reparada.

**Comment by gabrielziegler3** [comment]
Revisado e aceito!
