### ISSUE TITLE
Criação de documentação de estudo da US02

### ISSUE THREAD

**Issue by thiagoiferreira** [fga-eps-mds/2019.1-PyLearner#83]
# Criação de documento de estudo da US02
---
### Descrição:
Está task consiste na elaboração de uma documentação de comprovação de estudo para o tema da história de usuário designada. O objetivo desse estudo é que facilite a produção das histórias de usuário e tragam uma qualidade mais elevada das entregas, sendo corretas e precisas as informações passadas pelo bot.
Nessa task, o desenvolvedor deverá atacar o tema de importação de dados em JSON, explicitando o que é um JSON, como são estruturados os dados nesse tipo de arquivo e outros fatores relavantes ao assunto em geral. Em continuidade e partidindo para um viés mais técnico, deverá ser abordado o bruto da real utilização deste tipo de dado, que é sua importação, como fazê-la no python e quais flags podem ser usadas para a importação deste dado.

### Critérios de Aceitação
Para a aceitação deste documento, este deve seguir os seguintes padrões, lembrando que você tem total autonomia para implementar melhoras nesse modelo e isso é só o básico que a gente pensou necessário:
- [ ] O documento deve ser estruturado em tópicos e subtópicos
- [ ] O documento deve abordar a temática da US02 de forma correta e detalhada, de forma que possa servir de base para o desenvolvimento dos diálogos em RASA.
- [ ] O documento contém um detalhamento das funções e a forma de utilizá-las para provar o que o estudo foi aproveitado.

**Comment by Mexazonic** [comment]
Documento pronto e disponível para avaliação.
Link: https://github.com/fga-eps-mds/2019.1-PyLearner/blob/master/docs/Documento-da-US02.md
