### ISSUE TITLE
Detalhar as ferramenta de funcionalidades do backlog

### ISSUE THREAD

**Issue by joao15victor08** [fga-eps-mds/2019.1-PyLearner#93]
Detalhar quais ferramentas serão utilizadas em cada funcionalidade do backlog.

**Comment by gabrielziegler3** [comment]
@joao15victor08 ferramentas de cada epico detalhadas com links! [#50e8f44](https://github.com/fga-eps-mds/2019.1-PyLearner/commit/50e8f44d58714685aaf6f1ca4c178b2d763bd422)
